# World Happiness

## 1. Import Libraries and Dependencies

In [1]:
# Import necessary libraries and dependencies
import pandas as pd
import numpy as np
from pathlib import Path

%matplotlib inline

## 2. Set File Path to CSV using Pathlib

In [2]:
# Create reference to CSV file
data = Path(r'C:\Users\TribThapa\Desktop\Thapa\ResearchFellow\Courses\FinTech_Bootcamp_MonashUni2021\monu-mel-virt-fin-pt-05-2021-u-c\Activities\Week 4\2\16-culmination-03\Resources\world_happiness.csv')

## 3. Import CSV into Pandas DataFrame

In [3]:
# Import the CSV into a pandas DataFrame
data_df = pd.read_csv(data)
data_df.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

## 4. Set Index and Sort Index in Ascending Order

In [4]:
# Set index to Country
data_idx_df = data_df.set_index('Country')
data_idx_df

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
Country,,,,,,,,,,,
Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...
Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

In [5]:
# Sort the new dataframe alphabetically
data_idx_sort_df = data_idx_df.sort_index(ascending=True)
data_idx_sort_df

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
Country,,,,,,,,,,,
Afghanistan,141,3.794,3.873661,3.714338,0.401477,0.581543,0.180747,0.106180,0.311871,0.061158,2.150801
Albania,109,4.644,4.752464,4.535536,0.996193,0.803685,0.731160,0.381499,0.201313,0.039864,1.490442
Algeria,53,5.872,5.978286,5.765714,1.091864,1.146217,0.617585,0.233336,0.069437,0.146096,2.567604
Angola,140,3.795,3.951642,3.638358,0.858428,1.104412,0.049869,0.000000,0.097926,0.069720,1.614482
Argentina,24,6.599,6.690085,6.507915,1.185295,1.440451,0.695137,0.494519,0.109457,0.059740,2.614005
...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,82,5.250,5.370032,5.129968,1.128431,1.431338,0.617144,0.153997,0.065020,0.064491,1.789464
Vietnam,94,5.074,5.147281,5.000719,0.788548,1.277491,0.652169,0.571056,0.234968,0.087633,1.462319
Yemen,146,3.593,3.692750,3.493250,0.591683,0.935382,0.310081,0.249464,0.104125,0.056767,1.345601
Zambia,116,4.514,4.644106,4.383894,0.636407,1.003187,0.257836,0.461603,0.249580,0.078214,1.826705
Zimbabwe,138,3.875,3.978700,3.771300,0.375847,1.083096,0.196764,0.336384,0.189143,0.095375,1.597970

## 5. Select the Happiness Score for Vietnam

In [6]:
# Grab the data contained within the row of a country of your choice and the "Happiness.Score" column
CountryName = 'Vietnam'

viet = data_idx_sort_df.loc[[CountryName], 'Happiness.Score']
#viet

# Print the result as "<country's name> happiness score for 2017 was <happiness score>"
print(f"{CountryName}'s happiness score for 2017 was {viet[0]}. ")

Vietnam's happiness score for 2017 was 5.07399988174438.

## 6. Select the Happiness Rank and Score for Belgium, Belize, Benin, Bhutan, and Bolivia

In [7]:
# Select the columns "Happiness.Rank" and "Happiness.Score" for 'Belgium', 'Belize', 'Benin', 'Bhutan', and 'Bolivia'
cols = ['Happiness.Rank', 'Happiness.Score']

a = data_idx_sort_df.loc[['Belgium', 'Belize', 'Benin','Bhutan', 'Bolivia'], cols]
a

         Happiness.Rank  Happiness.Score
Country
Belgium              17            6.891
Belize               50            5.956
Benin               143            3.657
Bhutan               97            5.011
Bolivia              58            5.823

## 7. Select the Freedom and Government Trust for Every Country

In [8]:
data_idx_sort_df.columns

Index(['Happiness.Rank', 'Happiness.Score', 'Whisker.high', 'Whisker.low',
       'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.',
       'Freedom', 'Generosity', 'Trust..Government.Corruption.',
       'Dystopia.Residual'],
      dtype='object')

In [9]:
# Select the columns "Freedom" and "Trust..Government.Corruption." for each row/country
new_df = data_idx_sort_df[['Freedom', 'Trust..Government.Corruption.']]
new_df

              Freedom  Trust..Government.Corruption.
Country
Afghanistan  0.106180                       0.061158
Albania      0.381499                       0.039864
Algeria      0.233336                       0.146096
Angola       0.000000                       0.069720
Argentina    0.494519                       0.059740
...               ...                            ...
Venezuela    0.153997                       0.064491
Vietnam      0.571056                       0.087633
Yemen        0.249464                       0.056767
Zambia       0.461603                       0.078214
Zimbabwe     0.336384                       0.095375

[155 rows x 2 columns]

## 8. Select all the Countries Where GDP is Greater than or Equal to 1.6

In [10]:
# Select the countries where the "Economy..GDP.per.Capita" is greater than or equal to 1.6 using the loc function
GDP_df = data_idx_sort_df.loc[data_idx_sort_df['Economy..GDP.per.Capita.'] >= 1.6]
GDP_df

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
Country,,,,,,,,,,,
Kuwait,39,6.105,6.191957,6.018043,1.632952,1.259699,0.632106,0.496338,0.228290,0.215160,1.640425
Luxembourg,18,6.863,6.923686,6.802314,1.741944,1.457584,0.845089,0.596628,0.283181,0.318834,1.619512
Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
Qatar,35,6.375,6.568477,6.181523,1.870766,1.274297,0.710098,0.604131,0.330474,0.439299,1.145464
Singapore,26,6.572,6.636723,6.507277,1.692278,1.353814,0.949492,0.549841,0.345966,0.464308,1.216362
United Arab Emirates,21,6.648,6.722047,6.573952,1.626343,1.266410,0.726798,0.608345,0.360942,0.324490,1.734704

In [11]:
GDP_df.describe(include='all')

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,23.333333,6.683333,6.772889,6.593777,1.696791,1.357555,0.776708,0.581784,0.318477,0.346342,1.605582
std,13.574486,0.490756,0.468633,0.517183,0.097793,0.114717,0.112042,0.050247,0.052873,0.091567,0.407951
min,1.000000,6.105000,6.191957,6.018043,1.616463,1.259699,0.632106,0.496338,0.228290,0.215160,1.145464
25%,18.750000,6.424250,6.585538,6.262962,1.627996,1.268382,0.714273,0.561537,0.295004,0.316681,1.317150
50%,23.500000,6.610000,6.679385,6.540615,1.662615,1.314056,0.761732,0.600379,0.338220,0.321662,1.629969
75%,32.750000,6.809250,6.873276,6.745223,1.729527,1.431641,0.832984,0.607292,0.357198,0.410597,1.711134
max,39.000000,7.537000,7.594445,7.479556,1.870766,1.533524,0.949492,0.635423,0.362012,0.464308,2.277027

## 9. Select all the Countries Where the Happiness Score is Greater than or Equal to 5 and GDP is Less than or Equal to 1

In [12]:
# Select the countries where the "Happiness.Score" is greater than or equal to 5, and "Economy..GDP.per.Capita" is less than or equal to 1
HappyCountries_df = data_idx_sort_df.loc[data_idx_sort_df['Happiness.Score'] >= 5]
HappyCountries_df

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
Country,,,,,,,,,,,
Algeria,53,5.872,5.978286,5.765714,1.091864,1.146217,0.617585,0.233336,0.069437,0.146096,2.567604
Argentina,24,6.599,6.690085,6.507915,1.185295,1.440451,0.695137,0.494519,0.109457,0.059740,2.614005
Australia,10,7.284,7.356651,7.211349,1.484415,1.510042,0.843887,0.601607,0.477699,0.301184,2.065211
Austria,13,7.006,7.070670,6.941330,1.487097,1.459945,0.815328,0.567766,0.316472,0.221060,2.138506
Azerbaijan,85,5.234,5.299287,5.168714,1.153602,1.152400,0.540776,0.398156,0.045269,0.180988,1.762482
...,...,...,...,...,...,...,...,...,...,...,...
United States,14,6.993,7.074657,6.911343,1.546259,1.419921,0.774287,0.505741,0.392579,0.135639,2.218113
Uruguay,28,6.454,6.545906,6.362094,1.217560,1.412228,0.719217,0.579392,0.175097,0.178062,2.172410
Uzbekistan,47,5.971,6.065538,5.876463,0.786441,1.548969,0.498273,0.658249,0.415984,0.246528,1.816914
Venezuela,82,5.250,5.370032,5.129968,1.128431,1.431338,0.617144,0.153997,0.065020,0.064491,1.789464
Vietnam,94,5.074,5.147281,5.000719,0.788548,1.277491,0.652169,0.571056,0.234968,0.087633,1.462319

In [13]:
HappyCountries_df.describe(include='all')

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
count,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000
mean,49.500000,6.054041,6.145078,5.963004,1.205908,1.328528,0.679461,0.453213,0.248414,0.139710,1.998798
std,28.434134,0.730625,0.721921,0.740855,0.296828,0.172136,0.152018,0.131149,0.134702,0.114790,0.460564
min,1.000000,5.004000,5.079335,4.918080,0.022643,0.672691,0.056916,0.095731,0.000000,0.000000,0.554633
25%,25.250000,5.350750,5.505011,5.258328,1.042563,1.239170,0.596442,0.381410,0.152324,0.049104,1.718153
50%,49.500000,5.959500,6.036506,5.862872,1.243267,1.367631,0.686700,0.473148,0.234393,0.097956,1.999052
75%,73.750000,6.576500,6.662542,6.501671,1.427421,1.450817,0.808202,0.561567,0.329779,0.207182,2.287021
max,98.000000,7.537000,7.622030,7.479556,1.870766,1.610574,0.949492,0.658249,0.611705,0.464308,3.117485